version: '3.7'
services:
  db:
    container_name: 'finalpostgre'
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: backend
      POSTGRES_DB: backend
      POSTGRES_PASSWORD: backend
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: